/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface XtestJSONReport {
  version: 1;
  generatedAt: string;
  passed: boolean;
  totals: {
    total: number;
    passed: number;
    failed: number;
    skipped: number;
    duration: number;
    [k: string]: unknown;
  };
  files: {
    file: string;
    passed: boolean;
    total: number;
    totalPass: number;
    totalFail: number;
    totalSkipped: number;
    duration: number;
    suites: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
